// core-js-compat reports the first version of each engine where a built-in is
// both available *and* compliant with the latest version of the spec. When
// validating, we only care about whether a built-in is available.
//
// This is a list of core-js modules that only fix compliance bugs in built-ins
// that have been available since ES5 (IE 9, Chrome 6, Firefox 4, Safari 5.1),
// and thus should never be reported. It has been generated by comparing
// core-js-compat with @mdn/browser-compat-data: when updating core-js-compat,
// check if it introduced new modules that should be added here.
export const complianceFixes = new Set([
  "es.array.concat",
  "es.array.every",
  "es.array.filter",
  "es.array.for-each",
  "es.array.index-of",
  "es.array.is-array",
  "es.array.join",
  "es.array.last-index-of",
  "es.array.map",
  "es.array.push",
  "es.array.reduce",
  "es.array.reduce-right",
  "es.array.reverse",
  "es.array.slice",
  "es.array.some",
  "es.array.sort",
  "es.array.splice",
  "es.array.unshift",
  "es.date.now",
  "es.date.to-string",
  "es.error.to-string",
  "es.json.parse",
  "es.json.stringify",
  "es.number.constructor",
  "es.number.to-exponential",
  "es.number.to-fixed",
  "es.number.to-precision",
  "es.object.define-properties",
  "es.object.define-property",
  "es.object.freeze",
  "es.object.get-own-property-descriptor",
  "es.object.get-own-property-names",
  "es.object.get-prototype-of",
  "es.object.is-extensible",
  "es.object.is-frozen",
  "es.object.is-sealed",
  "es.object.keys",
  "es.object.prevent-extensions",
  "es.object.seal",
  "es.object.to-string",
  "es.regexp.constructor",
  "es.regexp.exec",
  "es.regexp.test",
  "es.regexp.to-string",
  "es.string.big",
  "es.string.blink",
  "es.string.bold",
  "es.string.fixed",
  "es.string.fontcolor",
  "es.string.fontsize",
  "es.string.italics",
  "es.string.link",
  "es.string.match",
  "es.string.replace",
  "es.string.search",
  "es.string.small",
  "es.string.split",
  "es.string.strike",
  "es.string.sub",
  "es.string.sup",

  // `Error` has always been available, core-js only adds support for its
  // `cause` option.
  "es.error.cause",

  // Array.prototype[Symbol.unscopables] only affects `with` statements.
  "es.array.unscopables.flat",
  "es.array.unscopables.flat-map",
]);

// Obsolete proposals that have been superseded by a stable built-in with the
// same name, but are still listed by core-js for backwards compatibility.
export const obsoleteProposals = new Set([
  // Superseded by es.string.at-alternative
  "esnext.string.at",
]);
